### ISSUE TITLE
Unable to find google plist file

### ISSUE THREAD

**Issue by IamSubhashish** [hosituanit/clockon-clockoff-face-recognition#2]
Can you please let me know how to configure the firebase and GoogleService-Info.plist file. As it is missing from the current project.
Currently, the app is not working for me and I am looking for something from which I can achieve real-time face recognition without the internet.

Thanks

**Comment by hosituan** [comment]
Which error are you having? GoogleService-Info.plist file is just the way to connect firebase database, it is not the core of application. Did you download the modelFacenet.pb file?

**Comment by IamSubhashish** [comment]
Yes, I did I downloaded that and placed it inside Tensorflow/Graph.
Is there any way I can run this app offline without firebase  I am new to this

**Comment by hosituan** [comment]
I have configured for it run local by RealM database, you can use without firebase database. I deleted my Google plist file, you can revert to that commit to get it back and build the app. But you can't connect to database, because you don't have permission.

**Comment by IamSubhashish** [comment]
Thanks for your help I will have a look at the implementation of the RealM database. and see if that works for me
